version: '3.4'

# we use env vars values from host. see source_env.sh
x-proxies: &proxies
  no_proxy:
  http_proxy:
  https_proxy:
  NO_PROXY:
  HTTP_PROXY:
  HTTPS_PROXY:

x-airflow-connections: &airflow-connections
  DEV_DB_URL:
  AIRFLOW_DB_PATH:
  AIRFLOW_DB_URL:
  ETL_DB_URL:

x-airflow-volumes: &airflow-volumes
  volumes:
    - ./etl:/etl
    - ./etl/logs:/opt/airflow/logs
    - ./alembic:/alembic

services:

  # Redis as a Celery broker
  airflow-broker:
    image: redis:6.0.5-alpine

  # DB for the Airflow metadata
  airflow-db:
    build:
      context: ./
      dockerfile: docker/airflow-db/Dockerfile
    volumes:
      - postgres-airflow:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_DB_DB}
    ports:
      - 5431:5432

  # Main container with Airflow Webserver, Scheduler, Celery Flower
  airflow:
    build:
      context: ./
      dockerfile: docker/airflow/Dockerfile
      args:
        <<: *proxies
    <<: *airflow-volumes
    environment:
      <<: *airflow-connections
    depends_on:
      - airflow-db
      - airflow-broker
    ports:
      # Celery Flower
      - 5551:5555
      # Airflow Webserver
      - 8080:8080

  # Celery worker, will be scaled using `--scale=n`
  airflow-worker:
    build:
      context: ./
      dockerfile: docker/worker/Dockerfile
    <<: *airflow-volumes
    environment:
      <<: *airflow-connections
    # wait for Airflow DB to be be initialized in airflow container
    command: >
       -c " sleep 10 &&
           /entrypoint worker"
    ports:
      - 8793:8793
    depends_on:
      - airflow
      - airflow-db
      - airflow-broker

volumes:
  postgres-airflow:
