
# build docs from docstrings and markdown-file in folder docs
# publish them as github pages
#
#note for myself
#
# Do not forget to set git branch `gh-pages` as source for github pages.
# This branch auto-updated by `mkdocs gh-deploy`
#
name: static source code checks
on:
  push:
    branches:
      - main
      - master
jobs:
  static:
    env:
      PRIMARY_PYTHON_VERSION: '3.12'
      ARFLOW_VERSION: '3.0.4'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PRIMARY_PYTHON_VERSION  }}
      - uses: andgineer/uv-venv@v1
      - run: |
          uv pip install "apache-airflow[celery,postgres,pandas,redis]==${ARFLOW_VERSION}" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-${ARFLOW_VERSION}/constraints-${PRIMARY_PYTHON_VERSION}.txt"
          uv pip install -r docker/airflow/requirements.txt
          uv pip install -r test_requirements.txt
      - run: pre-commit run --verbose --all-files
